import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/layout/Header'
import Hero from '@/components/sections/Hero'
import Header from '@/components/layout/Header'
import Current from '@/components/sections/Current'
import News from '@/components/sections/News'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Header />
        <Hero/>
        <Current/>
        <News/>
      </main>
    </>
  )
}
